services:
  redis:
    image: redis:7-alpine
    container_name: redis-fare
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-fare
    ports:
      - "5672:5672"
      - "15672:15672"